### PR TITLE
Add parameters 'ignore_file_names' and 'enable_storage_optimizer' to setTdlibParameters

### PR DESCRIPTION
**Pull request by dev-rio**
…setTdlibParameters

### CODE REVIEW

**Comment by AYMENJD** [comment]
They are removed since TDLib v1.8.24.

**Comment by dev-rio** [comment]
When the library is called and run file bot
Show problem

TypeError: TDLibFunctions.setTdlibParameters() got an unexpected keyword
argument 'enable_storage_optimizer'

TypeError: TDLibFunctions.setTdlibParameters() got an unexpected keyword
argument 'ignore_file_names'

**Comment by AYMENJD** [comment]
Yes, and the client still pass these parameters. I will fix it soon.

**Comment by AYMENJD** [comment]
This should be fixed now in Pytdbot v0.8.8.

**Comment by dev-rio** [comment]
Mean in pypi?

**Comment by AYMENJD** [comment]
Yes, just update Pytdbot.

**Comment by dev-rio** [comment]
Yes, I am install the version on github

**Pull request closed without merging**
